import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Gastos Mensais V3",
	description: "Generated by create next app",
};

type RootLayoutParams = Readonly<{ children: React.ReactNode; }>

export default function RootLayout({ children }: RootLayoutParams) {
	return (
		<html lang="en">
			<body className={inter.className}>{children}</body>
		</html>
	);
}
